name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "dependencies"
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "🔒 Security"
    labels:
      - "security"
  - title: "🏗️ CI/CD"
    labels:
      - "ci"
      - "github-actions"
  - title: "🐳 Docker"
    labels:
      - "docker"
  - title: "⚡ Performance"
    labels:
      - "performance"
      - "optimization"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
      - "bug"
      - "security"
  default: patch

template: |
  ## Changes

  $CHANGES

  ## Installation

  ### From Source
  ```bash
  git clone https://github.com/grok-rs/waitup.git
  cd waitup
  cargo install --path .
  ```

  ### Docker
  ```bash
  # Build from source
  docker build -t waitup:v$RESOLVED_VERSION .
  docker run --rm waitup:v$RESOLVED_VERSION --help

  # Or build Alpine variant
  docker build -f Dockerfile.alpine -t waitup:v$RESOLVED_VERSION-alpine .
  ```

  ### Binary Downloads
  Download the appropriate binary for your platform from the assets below.

  **Verify downloads with SHA256 checksums:**
  ```bash
  sha256sum -c waitup-*.sha256
  ```

  ## Supported Platforms

  | Platform | Architecture | Binary |
  |----------|-------------|--------|
  | Linux | x86_64 | `waitup-$RESOLVED_VERSION-x86_64-linux.tar.gz` |
  | Linux (musl) | x86_64 | `waitup-$RESOLVED_VERSION-x86_64-linux-musl.tar.gz` |
  | Linux | ARM64 | `waitup-$RESOLVED_VERSION-aarch64-linux.tar.gz` |
  | macOS | x86_64 | `waitup-$RESOLVED_VERSION-x86_64-macos.tar.gz` |
  | macOS | ARM64 | `waitup-$RESOLVED_VERSION-aarch64-macos.tar.gz` |
  | Windows | x86_64 | `waitup-$RESOLVED_VERSION-x86_64-windows.zip` |

  ## Shell Completions

  Each binary release includes shell completion scripts in the `completions/` directory:
  - `waitup.bash` - Bash completion
  - `_waitup` - Zsh completion
  - `waitup.fish` - Fish completion
  - `waitup.ps1` - PowerShell completion

  ## What's Next?

  - 📖 Check the [repository documentation](https://github.com/grok-rs/waitup/tree/main/docs)
  - 🐛 Report issues on [GitHub](https://github.com/grok-rs/waitup/issues)
  - 💬 Join the discussion in [Discussions](https://github.com/grok-rs/waitup/discussions)
  - 🤝 Contribute via [Pull Requests](https://github.com/grok-rs/waitup/pulls)

exclude-labels:
  - "skip-changelog"
  - "invalid"
  - "duplicate"
  - "question"
  - "wontfix"
  - "chore"
  - "dependencies"
  - "documentation"
  - "ci"

autolabeler:
  - label: "documentation"
    files:
      - "*.md"
      - "docs/**/*"
  - label: "ci"
    files:
      - ".github/workflows/*"
      - ".github/dependabot.yml"
  - label: "docker"
    files:
      - "Dockerfile*"
      - "docker-compose.yml"
  - label: "dependencies"
    files:
      - "Cargo.toml"
      - "Cargo.lock"
  - label: "rust"
    files:
      - "src/**/*"
      - "examples/**/*"
      - "tests/**/*"
