name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "dependencies"
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "🔒 Security"
    labels:
      - "security"
  - title: "🏗️ CI/CD"
    labels:
      - "ci"
      - "github-actions"
  - title: "🐳 Docker"
    labels:
      - "docker"
  - title: "⚡ Performance"
    labels:
      - "performance"
      - "optimization"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
      - "bug"
      - "chore"
      - "dependencies"
      - "documentation"
      - "ci"
      - "security"
  default: patch

template: |
  ## Changes

  $CHANGES

  ## Installation

  ### Cargo
  ```bash
  cargo install wait-for
  ```

  ### Docker
  ```bash
  # Standard image
  docker pull ghcr.io/grok-rs/wait-for:v$RESOLVED_VERSION

  # Alpine image (smaller)
  docker pull ghcr.io/grok-rs/wait-for:v$RESOLVED_VERSION-alpine
  ```

  ### Binary Downloads
  Download the appropriate binary for your platform from the assets below.

  **Verify downloads with SHA256 checksums:**
  ```bash
  sha256sum -c wait-for-*.sha256
  ```

  ## Supported Platforms

  | Platform | Architecture | Binary |
  |----------|-------------|--------|
  | Linux | x86_64 | `wait-for-$RESOLVED_VERSION-x86_64-linux.tar.gz` |
  | Linux (musl) | x86_64 | `wait-for-$RESOLVED_VERSION-x86_64-linux-musl.tar.gz` |
  | Linux | ARM64 | `wait-for-$RESOLVED_VERSION-aarch64-linux.tar.gz` |
  | macOS | x86_64 | `wait-for-$RESOLVED_VERSION-x86_64-macos.tar.gz` |
  | macOS | ARM64 | `wait-for-$RESOLVED_VERSION-aarch64-macos.tar.gz` |
  | Windows | x86_64 | `wait-for-$RESOLVED_VERSION-x86_64-windows.zip` |

  ## Shell Completions

  Each binary release includes shell completion scripts in the `completions/` directory:
  - `wait-for.bash` - Bash completion
  - `_wait-for` - Zsh completion
  - `wait-for.fish` - Fish completion
  - `wait-for.ps1` - PowerShell completion

  ## What's Next?

  - 📖 Check the [documentation](https://docs.rs/wait-for)
  - 🐛 Report issues on [GitHub](https://github.com/grok-rs/wait-for/issues)
  - 💬 Join the discussion in [Discussions](https://github.com/grok-rs/wait-for/discussions)

exclude-labels:
  - "skip-changelog"
  - "invalid"
  - "duplicate"
  - "question"
  - "wontfix"

autolabeler:
  - label: "documentation"
    files:
      - "*.md"
      - "docs/**/*"
  - label: "ci"
    files:
      - ".github/workflows/*"
      - ".github/dependabot.yml"
  - label: "docker"
    files:
      - "Dockerfile*"
      - "docker-compose.yml"
  - label: "dependencies"
    files:
      - "Cargo.toml"
      - "Cargo.lock"
  - label: "rust"
    files:
      - "src/**/*"
      - "examples/**/*"
      - "tests/**/*"
