# Reasonable Clippy configuration for waitup project
# This configuration balances code quality with practical development workflow

# ===== THRESHOLDS =====

# Cognitive complexity threshold - reasonable for most functions
cognitive-complexity-threshold = 20

# Type complexity threshold - allow reasonable complexity
type-complexity-threshold = 75

# Maximum number of arguments for functions - allow reasonable APIs
too-many-arguments-threshold = 6

# Maximum lines in functions - reasonable limit
too-many-lines-threshold = 100

# Enum variant name threshold - reasonable naming
enum-variant-name-threshold = 3

# Literal representation threshold
literal-representation-threshold = 65536

# Single char binding names threshold - allow common patterns
single-char-binding-names-threshold = 4

# Array size thresholds
array-size-threshold = 512000

# Size threshold for pass by value - reasonable for performance
pass-by-value-size-limit = 256

# ===== DOCUMENTATION =====

# Don't require documentation for all items (too strict for development)
# Will be enforced selectively via CI for public APIs
missing-docs-in-crate-items = false

# ===== PERFORMANCE =====

# Don't break exported API unnecessarily during development
avoid-breaking-exported-api = false

# ===== LINT CATEGORIES CONFIGURATION =====
# Note: These are typically configured via command line in CI/hooks
# This file focuses on thresholds and behavioral settings

# Allow some common patterns that restriction lints complain about
# These will be managed via selective allows in source code rather than global config
