# cargo-release configuration for waitup
# Use with: cargo release [patch|minor|major]

[workspace]
allow-branch = ["main", "master"]
pre-release-commit-message = "chore: Release {{crate_name}} version {{version}}"
pro-release-commit-message = "chore: Start next development iteration {{version}}"
tag-message = "Release {{crate_name}} version {{version}}"
tag-prefix = "v"
push-remote = "origin"

# Pre-release checks
pre-release-replacements = [
  {file="CHANGELOG.md", search="## \\[Unreleased\\]", replace="## [Unreleased]\n\n## [{{version}}] - {{date}}"},
]

# Dependencies check
dev-version = false
shared-version = false

# Enable all the steps we want
sign-commit = false
sign-tag = false
push = true
publish = true

# Package-specific settings
[[package]]
name = "waitup"

# Verify tests pass before release
pre-release-hook = [
  "cargo test --all-features",
  "cargo clippy --all-targets --all-features -- -D warnings",
  "cargo fmt --all -- --check",
  "cargo doc --no-deps --all-features",
]

# Post-release actions
post-release-hook = [
  "echo 'Release {{version}} completed successfully!'",
  "echo 'Published to: https://crates.io/crates/{{crate_name}}'",
  "echo 'Create GitHub release: https://github.com/grok-rs/waitup/releases/new?tag=v{{version}}&title=Release%20v{{version}}'",
]
