# Rust formatting configuration for waitup project (stable-compatible)

# Basic formatting
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports (stable options only)
reorder_imports = true

# Formatting details
use_small_heuristics = "Default"
merge_derives = true
use_field_init_shorthand = true

# Newlines
newline_style = "Unix"

# Match expressions
match_block_trailing_comma = false
