name: 🐛 Bug Report
description: Report a bug to help us improve waitup
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the form below to help us understand and reproduce the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following before submitting this bug report.
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have read the documentation and confirmed this is unexpected behavior
          required: true
        - label: I am using the latest version of waitup
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen instead.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue.
      placeholder: |
        1. Run command: `waitup localhost:8080`
        2. Wait for timeout
        3. Observe error message
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened, including any error messages
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: waitup Version
      description: What version of waitup are you using?
      placeholder: "v1.0.2 (run `waitup --version`)"
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install waitup?
      options:
        - Cargo (crates.io)
        - Docker/Container
        - Pre-built binary
        - Built from source
        - Package manager (specify in additional context)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      value: |
        - OS: [e.g., Ubuntu 22.04, macOS 13.0, Windows 11]
        - Architecture: [e.g., x86_64, aarch64]
        - Container Runtime: [if applicable, e.g., Docker 24.0.0, Podman]
        - Kubernetes Version: [if applicable]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command and Output
      description: Please provide the exact command you ran and the output/error
      placeholder: |
        Command:
        $ waitup localhost:8080 --verbose

        Output:
        [paste output here]
      render: shell
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Additional Logs
      description: Any additional logs, verbose output, or debugging information
      placeholder: Paste any relevant logs here
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Network configuration details
        - Firewall settings
        - Related service configurations
        - Screenshots (if applicable)

  - type: checkboxes
    id: willingness
    attributes:
      label: Contribution
      description: Are you willing to help fix this issue?
      options:
        - label: I am willing to submit a pull request to fix this bug
