blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://docs.rs/waitup
    about: Read the full API documentation and examples
  - name: 💬 Discussions
    url: https://github.com/grok-rs/waitup/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/grok-rs/waitup/security/advisories/new
    about: Report security vulnerabilities privately
