# Cargo configuration for waitup project
# This file configures cargo behavior and sets up strict linting by default

[alias]
# Development aliases
dev-check = "check --all-targets --all-features"
dev-test = "test --all-features"
dev-fmt = "fmt --all"
dev-clippy = "clippy --all-targets --all-features"

# Strict linting aliases (matching CI exactly)
lint = """clippy --all-targets --all-features -- \
  -D warnings \
  -D clippy::pedantic \
  -D clippy::nursery \
  -W clippy::restriction \
  -D clippy::unwrap_used \
  -D clippy::expect_used \
  -D clippy::panic \
  -D clippy::todo \
  -D clippy::unimplemented \
  -W clippy::dbg_macro \
  -W clippy::print_stdout \
  -W clippy::print_stderr"""
lint-fix = """clippy --all-targets --all-features --fix -- \
  -D warnings \
  -D clippy::pedantic \
  -D clippy::nursery \
  -W clippy::restriction \
  -D clippy::unwrap_used \
  -D clippy::expect_used \
  -D clippy::panic \
  -D clippy::todo \
  -D clippy::unimplemented \
  -W clippy::dbg_macro \
  -W clippy::print_stdout \
  -W clippy::print_stderr"""

# Documentation aliases (matching CI)
doc-check = "doc --no-deps --all-features --document-private-items"
doc-check-strict = "doc --no-deps --all-features --document-private-items"
doc-open = "doc --no-deps --all-features --document-private-items --open"

# Security and audit aliases (matching CI)
security-audit = "audit --deny warnings"
audit-strict = "audit --deny warnings"
deny-check = "deny check"
unused-deps = "machete"

# Testing aliases (matching CI)
test-all = "test --all-features --workspace"
test-lib = "test --lib --all-features"
test-integration = "test --test integration_tests"
test-doc = "test --doc --all-features"
test-examples = "check --examples"

# Release preparation
pre-release = [
    "fmt --all -- --check",
    "clippy --all-targets --all-features -- -D warnings -D clippy::pedantic -W clippy::nursery",
    "test --all-features --workspace",
    "doc --no-deps --all-features --document-private-items",
    "cargo-audit --deny warnings"
]

# Full quality check (equivalent to CI workflows)
ci-check = [
    "check --all-targets --all-features",
    "fmt --all -- --check",
    "lint",
    "test --lib --all-features",
    "test --test integration_tests",
    "test --doc --all-features",
    "check --examples",
    "unused-deps",
    "audit-strict",
    "deny-check"
]

# Quick individual commands for local development
fmt-check = "fmt --all -- --check"
build-check = "check --all-targets --all-features"

[build]
# Use all available CPU cores for builds (0 means use all cores)
# Note: Commented out as 0 is not supported in older cargo versions
# jobs = 0

[term]
# Enable colored output
color = "always"

[cargo-new]
# Default to current edition
edition = "2021"

[env]
# Set strict Rust flags for development (commented out for now - too strict for initial setup)
# RUSTFLAGS = "-D warnings -D rust-2018-idioms -D clippy::perf"
# RUSTDOCFLAGS = "-D warnings -D rustdoc::broken_intra_doc_links"

# [target.x86_64-unknown-linux-gnu]
# # Linux-specific settings
# rustflags = [
#     "-C", "link-arg=-Wl,--as-needed",
#     "-C", "link-arg=-Wl,-z,relro,-z,now",
# ]

# [target.x86_64-pc-windows-msvc]
# # Windows-specific settings
# rustflags = [
#     "-C", "target-feature=+crt-static",
# ]

[registries.crates-io]
protocol = "sparse"

# [source.crates-io]
# replace-with = "vendored-sources"

# [source.vendored-sources]
# directory = "vendor"

# HTTP settings
[http]
check-revoke = true
timeout = 30
low-speed-limit = 10
multiplexing = true
